[2023-05-15T18:22:56.763918+00:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /var/www/vendor/symfony/error-handler/DebugClassLoader.php:338)"} []
[2023-05-15T18:22:56.765595+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"sanatorium_db_test","charset":"utf8mb4"} {"params":{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"sanatorium_db_test","charset":"utf8mb4"}} []
[2023-05-15T18:22:56.769640+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2023-05-15T18:22:56.771221+00:00] doctrine.INFO: Disconnecting [] []
[2023-05-15T18:22:56.771718+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"sanatorium_db_test","charset":"utf8mb4"} {"params":{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"sanatorium_db_test","charset":"utf8mb4"}} []
[2023-05-15T18:22:56.772959+00:00] console.CRITICAL: Error thrown while running command "doctrine:migrations:migrate --env=test". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'sanatorium_db_test'" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'sanatorium_db_test' at /var/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'sanatorium_db_test' at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'sanatorium_db_test' at /var/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:34)","command":"doctrine:migrations:migrate --env=test","message":"An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'sanatorium_db_test'"} []
[2023-05-15T18:22:56.775001+00:00] console.DEBUG: Command "doctrine:migrations:migrate --env=test" exited with code "1049" {"command":"doctrine:migrations:migrate --env=test","code":1049} []
[2023-05-15T18:26:06.301219+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"sanatorium_test_test","charset":"utf8mb4"} {"params":{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"sanatorium_test_test","charset":"utf8mb4"}} []
[2023-05-15T18:26:06.303773+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"} {"params":{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"charset":"utf8mb4"}} []
[2023-05-15T18:26:06.305548+00:00] doctrine.INFO: Disconnecting [] []
[2023-05-15T18:26:06.306195+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"sanatorium_test_test","charset":"utf8mb4"} {"params":{"url":"<redacted>","dbname_suffix":"_test","driver":"pdo_mysql","host":"db","port":3306,"user":"root","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"collation":"utf8mb4_unicode_ci"},"dbname":"sanatorium_test_test","charset":"utf8mb4"}} []
[2023-05-15T18:26:06.307894+00:00] console.CRITICAL: Error thrown while running command "doctrine:migrations:migrate --env=test". Message: "An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'sanatorium_test_test'" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'sanatorium_test_test' at /var/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'sanatorium_test_test' at /var/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'sanatorium_test_test' at /var/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:34)","command":"doctrine:migrations:migrate --env=test","message":"An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'sanatorium_test_test'"} []
[2023-05-15T18:26:06.309508+00:00] console.DEBUG: Command "doctrine:migrations:migrate --env=test" exited with code "1049" {"command":"doctrine:migrations:migrate --env=test","code":1049} []
